spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sfg_dev?useSSL=false&allowPublicKeyRetrieval=True&createDatabaseIfNotExist=true
    username: sfg_dev_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
#    generate-ddl: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always